noProblemsMention = "- no 'problems' keywords detected: {{.Keywords}}"
noTodayMention = "- no 'today' keywords detected: {{.Keywords}}"
noYesterdayMention = "- no 'yesterday' keywords detected: {{.Keywords}}"
