addStandupTime = "Updated standup deadline to {{.Deadline}}"
couldNotShowDeadline = "Can not show channel deadline"
createStanduperFailed = "Could not add you to standup team"
deadlineNotSet = "Could not change channel deadline"
failedLeaveStandupers = "Could not remove you from standup team"
leaveStanupers = "You no longer have to submit standups, thanks for all your standups and messages"
listNoStandupers = "No standupers in the team, /join to start standuping"
noProblemsMention = "- no 'problems' keywords detected: {{.Keywords}}"
noTodayMention = "- no 'today' keywords detected: {{.Keywords}}"
noYesterdayMention = "- no 'yesterday' keywords detected: {{.Keywords}}"
notStanduper = "You do not standup yet"
removeStandupTime = "Standup deadline removed"
selectChannelFailed = "Could not add you to standup team, try kick and re-add me to the channel"
showNoStandupTime = "Standup deadline is not set"
showStandupTime = "Standup deadline set to {{.Deadline}}"
welcomeNoDedline = "Welcome to the standup team, no standup deadline has been setup yet"
welcomeWithDedline = "Welcome to the standup team, please, submit your standups no later than {{.Deadline}}"
wrongDeadlineFormat = "Could not recognize deadline time. Use 1pm or 13:00 formats"
youAlreadyStandup = "You are already a part of standup team"

[showStandupers]
few = "{{.Standupers}} submit standups in the team"
many = "{{.Standupers}} submit standups in the team"
one = "Only {{.Standupers}} standups in the team, /join to start standuping"
other = "{{.Standupers}} submit standups in the team"
two = "{{.Standupers}} submit standups in the team"
