version: '3'

services:

  db:
    image: percona/percona-server:5.7 
    restart: on-failure
    volumes:
      - "./docker:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: comedian
      MYSQL_USER: comedian
      MYSQL_PASSWORD: comedian

  comedian:
    image: anatoliyfedorenko/comedian:2.17
    restart: on-failure
    ports:
      - 8080:8080
    links:
      - db:db
    environment:
      TZ: Asia/Bishkek
      COMEDIAN_SLACK_TOKEN: ${COMEDIAN_SLACK_TOKEN}
      COMEDIAN_COLLECTOR_TOKEN: ${COMEDIAN_COLLECTOR_TOKEN}
      COMEDIAN_COLLECTOR_URL: ${COMEDIAN_COLLECTOR_URL}
      COMEDIAN_DATABASE: comedian:comedian@tcp(db:3306)/comedian?parseTime=true
      COMEDIAN_HTTP_BIND_ADDR: ${COMEDIAN_HTTP_BIND_ADDR}
      COMEDIAN_REMINDER_REPEATS_MAX: "2"
      COMEDIAN_REMINDER_TIME: "3"
      COMEDIAN_NOTIFIER_INTERVAL: ${COMEDIAN_NOTIFIER_INTERVAL}
      COMEDIAN_ENABLE_TEAM_MONITORING: "true"
      COMEDIAN_REPORT_TIME: "20:06"
      COMEDIAN_REPORTING_CHANNEL: ${COMEDIAN_REPORTING_CHANNEL}
      COMEDIAN_MANAGER_SLACK_USER_ID: "UB9AE7CL9"
      COMEDIAN_LANGUAGE: "ru_RU"
      COMEDIAN_SLACK_DOMAIN: "maddevs"  
    depends_on:
      - db
