version: '3'

services:

  db:
    image: percona/percona-server:5.7 
    restart: on-failure
    volumes:
      - "./docker:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: comedian
      MYSQL_USER: comedian
      MYSQL_PASSWORD: comedian

  comedian:
    image: anatoliyfedorenko/comedian:latest
    restart: on-failure
    ports:
      - 8080:8080
    links:
      - db:db
    environment:
      TZ: Asia/Bishkek
      COMEDIAN_SLACK_TOKEN: ${COMEDIAN_SLACK_TOKEN}
      COMEDIAN_DATABASE: comedian:comedian@tcp(db:3306)/comedian?parseTime=true
      COMEDIAN_HTTP_BIND_ADDR: ${COMEDIAN_HTTP_BIND_ADDR}
      COMEDIAN_NOTIFIER_INTERVAL: ${COMEDIAN_NOTIFIER_INTERVAL}
      COMEDIAN_HTTP_BIND_ADDR: ${COMEDIAN_HTTP_BIND_ADDR}
      COMEDIAN_MANAGER_SLACK_USER_ID: ${COMEDIAN_MANAGER_SLACK_USER_ID}
      COMEDIAN_REPORT_TIME: ${COMEDIAN_REPORT_TIME}
      COMEDIAN_LANGUAGE: ${COMEDIAN_LANGUAGE}
      COMEDIAN_ENABLE_TEAM_MONITORING: ${COMEDIAN_ENABLE_TEAM_MONITORING}
      COMEDIAN_COLLECTOR_TOKEN: ${COMEDIAN_COLLECTOR_TOKEN}
      COMEDIAN_COLLECTOR_URL: ${COMEDIAN_COLLECTOR_URL}
      COMEDIAN_REPORTING_CHANNEL: ${COMEDIAN_REPORTING_CHANNEL}
      COMEDIAN_REMINDER_REPEATS_MAX: ${COMEDIAN_REMINDER_REPEATS_MAX}
      COMEDIAN_REMINDER_TIME: ${COMEDIAN_REMINDER_TIME}
    depends_on:
      - db
