version: '2'

services:

  db:
    image: percona/percona-server:5.7
    restart: on-failure
    command: --max_allowed_packet=32505856
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: comedian
      MYSQL_USER: comedian
      MYSQL_PASSWORD: comedian

  comedian:
    image: comedian:latest
    restart: on-failure
    links:
      - db:db
    expose:
      - 8080
    environment:
      COMEDIAN_DATABASE: comedian:comedian@tcp(db:3306)/comedian?parseTime=true
      COMEDIAN_HTTP_BIND_ADDR: 0.0.0.0:8080
      COMEDIAN_SLACK_CLIENT_ID: ${COMEDIAN_SLACK_CLIENT_ID}
      COMEDIAN_SLACK_CLIENT_SECRET: ${COMEDIAN_SLACK_CLIENT_SECRET}
    depends_on:
      - db
