version: '2.2'

networks:
  integration-tests:
    driver: bridge

services:

  adminer:
    container_name: comedian_adminer
    image: adminer:4.7.0
    restart: always
    ports:
      - 8081:8080
    networks:
      - integration-tests

  db:
    image: mysql:5.7
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: comedian
      MYSQL_PASSWORD: comedian
      MYSQL_DATABASE: comedian
    healthcheck:
      test: "mysql -ucomedian --password=comedian -e 'show databases;' |grep comedian"
      interval: 30s
      timeout: 20s
      retries: 10
    networks:
      - integration-tests

