[listNoStandupers]
hash = "sha1-b632f5be18aab00f18e7e524a5367ccdfdef01bb"
other = "No standupers in the team, /start to start standuping. "

[minutes]
few = "{{.time}} minutes"
hash = "sha1-5ae748c57f8a044c6a481e3b0d9304fe3b5446ef"
many = "{{.time}} minutes"
one = "{{.time}} minutes"
other = "{{.time}} minutes"

[showStandupTime]
hash = "sha1-154ef4fc36a38ceccf1a1238ed6abcbcc7b43ee9"
other = "Standup deadline is {{.Deadline}}"

[showStandupers]
few = "{{.Standupers}} submit standups in the team. "
hash = "sha1-dc9d26b759ed97660216e735b676a6996a0700e4"
many = "{{.Standupers}} submit standups in the team. "
one = "{{.Standupers}} submit standups in the team. "
other = "{{.Standupers}} submit standups in the team. "

[tagNonReporters]
few = "{{.users}} you have missed standup deadlines, shame!"
hash = "sha1-626cd784df0f80c1c2f83a488c1c6c32832a8e82"
many = "{{.users}} you have missed standup deadlines, shame!"
one = "{{.users}} you have missed standup deadlines, shame!"
other = "{{.users}} you have missed standup deadlines, shame!"

[warnNonReporters]
few = "{{.users}} you may miss the deadline in {{.minutes}}"
hash = "sha1-cc2c2df6f8c38a8ef85324ebc6f98ef590476c7e"
many = "{{.users}} you may miss the deadline in {{.minutes}}"
one = "{{.users}} you may miss the deadline in {{.minutes}}"
other = "{{.users}} you may miss the deadline in {{.minutes}}"
