userExist = "<@%v> уже назначен стендапером в этом канале\n"
addUserNoStandupTime = "Пользователь <@%s> теперь стендапит в этом канале, но не установлено время для стендапов!\n"
addUser = "Пользователь <@%s> теперь стендапит в этом канале!\n"
addAdmin = "Пользователь <@%s> добавлен как администратор\n"
accessDenied = "Эта команда не доступна вам так как у вас недостаточно прав!\n"

pmExists = "<@%s> уже ПМ в этом проекте!\n"
pmAdded = "<@%s> назначен ПМом в этом проекте!\n"

deleteUser = "Пользователь <@%s> больше не стендапит в этом канале.\n"
deleteAdmin = "<@%s> удален из администраторов.\n"
DeletePM = "<@%s> больше не ПМ проекта.\n"
listNoStandupers = "В этом канале нет стендаперов! Чтобы добавить кого-нибдуь, используйте слэш команду `/comedian_add`"
listNoAdmins = "В этом канале нет ПМов! Чтобы добавить нового ПМа, используйте слэш команду `/adminadd`"
listStandupers = "Стендаперы в канале: %v"
listAdmins = "Админы команды: %v"
listNoPMs = "В этом канале нет ПМов! Чтобы добавить ПМа, используйте слэш команду `/add`"
listPMs = "ПМы в проекте: %v"

addStandupTimeNoUsers = "<!date^%v^Срок для стендапов установлен на {time}, но в этом канале нет стендаперов|Срок для стендапов установлен на 12:00, но в этом канале нет стендаперов>"
addStandupTime = "<!date^%v^Срок для стендапов установлен на {time}|Срок для стендапов установлен на 12:00>"
removeStandupTimeWithUsers = "Время для стендапов в этом канале удалено, но остались стендаперы!"
removeStandupTime = "Стендап время для канала %s удалено" 

showNoStandupTime = "У этого канала до сих пор не установленно стендап время! Пожалуйста, установите время слэшкомандой `/standup_time_set`!"
showStandupTime = "<!date^%v^Срок для стендапов установлен на {time}|Срок для стендапов установлен на 12:00>"

wrongNArgs = "Неверное количество аргументов. Перепроверьте свои данные!"
reportByProjectAndUser = "Данный пользователь не установлен как стендапер в этом канале. Для начала добавьте его слэшкомандой `/comedian_add`"
reportOnProjectHead = "Полный отчет по проекту #%s с %v по %v:\n\n"
reportOnProjectCollectorData = "\nКоммитов за период: %v\nВорклогов за период: %v\n"
reportOnUserHead = "Полный отчет по пользователю <@%s> с %v по %v:\n\n"
reportOnProjectAndUserHead = "Отчет по пользователю <@%s> в проекте #%s с %v по %v:\n\n"

reportNoData = "Нет данных за данный период"
reportDate = "Отчет за %s:\n"
reportStandupFromUser = "\nСтендап от <@%s>:\n%s\n"
reportIgnoredStandup = "\n<@%s>: стендап пропущен!\n"
reportShowChannel = "В канале: <#%s>"
reportCollectorDataUser = "\nКоммитов: %v \nЧасов ворклогов: %v\n\n"
dateError1 = "Дата начала больше чем дата конца периуда"
dateError2 = "Дата конца отчёта указана в будущем времени"
userDidNotStandup = "<@%v> не написал стендап!\n"
userDidStandup = "<@%v> написал стендап!\n"
userDidNotStandupInChannel = "В #%v <@%v> не написал стендап!\n"
userDidStandupInChannel = "В #%v <@%v> написал стендап!\n"
PMAssigned = "Вас назначили админом Комедиана"
PMRemoved = "Вы больше не админ Комедиана"


helloManager = "Привет, менеджер!"
standupAccepted = "Отличная работа! Стендап принят! Бомби дальше!"

notifyNotAll = "В этом канале не все написали стендапы! Проигнорировали: %v"
notifyAllDone = "Поздравляю, сегодня все написали стендапы!"
notifyManagerAllDone = "<@%v>, в канале <#%s> все написали стендапы сегодня"
notifyManagerNotAll = "<@%v>, в канале <#%s> не все написали стендапы сегодня, игнорировали: %v."
notifyUsersWarning = "%v, команда всё еще ждет стендапы от вас! Осталось %v минут до дедлайна!"
notifyDirectMessage = "Привет, <@%s>! У тебя пропущен срок по стендапам в канале <#%s|%s>. Пожалуйста, напиши стендап! Чем скорее тем лучше!"


Worklogs = " ворклоги: %v %v "
WorklogsTime = "%v из %v"

noCommits = " коммиты: %v :shit: "
hasCommits = " коммиты: %v :tada: "

noStandup = " стендап :x: "
hasStandup = " стендап :heavy_check_mark: "

isRook = "<@%v> в #%v"

wrongUsernameError = "Кажется, вы допустили ошибку в имени пользователя. Пожалуйста, перепроверьте и попытайтесь еще раз!"

selectUsersToAdd = "Укажите пользователей, которых нужно добавить"
selectUsersToDelete = "Укажите пользователей, которых нужно удалить"
CanNotFindMember = "У <@%v> нет никакой роли в этом канале\n"
UserIsNotPM = "Пользователь <@%v> не ПМ в этом канале\n"
selectUsersToAddAsAdmin = "Укажите пользователей, которых нужно сделать админами"
noSuchUserInWorkspace = "Такого пользователя нет в вашем слаке"
userNotAdmin = "Этот пользователь не админ!"
wrongProjectName = "Неверное название проекта!"

DaysDivider = " по "
TimeDivider = " в " 
TimetableNoUsers = "Выберите стендаперов!"
TimetableCreated = "Расписание для <@%v> создано: %v \n"

TimetableUpdated = "Расписание для <@%v> обновлено: %v \n"
CanNotUpdateTimetable = "Не смог обновить расписание для <@%v>: %v\n"
NotAStanduper = "Кажется <@%v> не стендапит в этом канале!\n"
NoTimetableSet = "У <@%v> не установлено расписание!\n"
TimetableShow = "Расписание для <@%v>: %v\n"

CanNotDeleteTimetable = "Не смог создать расписание для <@%v>\n"
TimetableDeleted = "Расписание <@%v> успешно удалено! Теперь он стендапится по общему графику\n"

IndividualStandupersWarning = "Внимание <@%s>! Кажется, твоего стендапа до сих пор нет, а через %v минут уже последний срок! Поторопись!"
IndividualStandupersLate = "<@%v>, сроки пропущены! Пожалуйста, напиши стендап как можно скорее!"
EmptyTimetable = "Свободный график"

TimetableShowMonday = "| Понедельник %02d:%02d "
TimetableShowTuesday = "| Вторник %02d:%02d "
TimetableShowWednesday = "| Среда %02d:%02d "
TimetableShowThursday = "| Четверг %02d:%02d "
TimetableShowFriday = "| Пятница %02d:%02d "
TimetableShowSaturday = "| Суббота %02d:%02d "
TimetableShowSunday = "| Воскресенье %02d:%02d "
ComedianIsNotInChannel = "У меня нет информации об этом канале. Кажется, меня не добавили в канал... Если я в канале, пожалуйста добавьте меня заново и попробуйте еще раз!"


StandupHandleUserNotAssigned = "Не могу принять твой стендап так как ты не должен стендапить в этом канале. Попроси ПМа тебя добавить и попробуй снова! Буду ждать!"
StandupHandleOneDayOneStandup = "Один день - один стендап. Если хочешь поменять свой стендап, лучше отредактируй старый!"
StandupHandleCouldNotSaveStandup = "По какой-то непонятной причине я не смог сохранить твой стендап в базе. Прости пожалуйста и расскажи об этом ПМу!"
StandupHandleNoProblemsMentioned = "Не распознал ключевых слов блока 'проблемы'. Используйте следующие слова в стэндапе: 'проблем', 'трудност', 'затруднени', 'вопрос'"
StandupHandleNoYesterdayWorkMentioned = "Не распознал ключевых слов блока 'вчера'. Используйте следующие слова в стэндапе: 'вчера', 'пятниц', 'делал', 'сделано'"
StandupHandleNoTodayPlansMentioned = "Не распознал ключевых слов блока 'сегодня'. Используйте следующие слова в стэндапе: 'сегодня', 'собираюсь', 'план'"
StandupHandleUpdatedStandup = "Отредактировал стендап! Всё отлично!"
StandupHandleCreatedStandup = "Сохранил твой стендап! Всё супер!"

ErrorRooksReportWeekend = "Сегодня выходной! Следующий отчет в понедельник!"

ReportHeaderMonday = "Отчёт за прошлую пятницу и выходные"    
ReportHeader = "Отчет за вчерашний день" 


AccessAtLeastPM = "Доступ запрещен! Вам необходимо быть как минимум ПМом в этом проекте чтобы использовать эту команду"
AccessAtLeastAdmin = "Доступ запрещен! Вам необходимо быть как минимум админом в этом слаке чтобы использовать эту команду"
AccessAtLeastSuperAdmin = "Доступ запрещен! Вам необходимо быть суперадмином чтобы использовать эту команду"
AccessAtLeastAdminOrOwner = "Доступ запрещен! Вам необходимо быть как минимум админом в этом проекте или просматривать информацию только о себе чтобы использовать эту команду"
AccessAtLeastPMOrOwner = "Доступ запрещен! Вам необходимо быть как минимум ПМом в этом проекте или просматривать информацию только о себе чтобы использовать эту команду"