userExist = "<@%v> уже назначен стендапером в этом канале\n"
addUserNoStandupTime = "Пользователь <@%s> теперь стэндапит в этом канале, но не установлено время для стэндапов!\n"
addUser = "Пользователь <@%s> теперь стэндапит в этом канале!\n"
addAdmin = "Пользователь <@%s> добавлен как администратор\n"
accessDenied = "Эта команда не доступна вам так как у вас недостаточно прав!\n"

pmExists = "<@%s> уже ПМ в этом проекте!\n"
pmAdded = "<@%s> назначен ПМом в этом проекте!\n"

deleteUser = "Пользователь <@%s> больше не стэндапит в этом канале.\n"
deleteAdmin = "<@%s> удален из администраторов.\n"
listNoStandupers = "В этом канале нет стэндаперов! Чтобы добавить кого-нибдуь, используйте слэш команду `/comedian_add`"
listNoAdmins = "В этом канале нет ПМов! Чтобы добавить нового ПМа, используйте слэш команду `/adminadd`"
listStandupers = "Стэндаперы в канале: %v"
listAdmins = "Админы команды: %v"

addStandupTimeNoUsers = "<!date^%v^Срок для стэндапов установлен на {time}, но в этом канале нет стэндаперов|Срок для стэндапов установлен на 12:00, но в этом канале нет стэндаперов>"
addStandupTime = "<!date^%v^Срок для стэндапов установлен на {time}|Срок для стэндапов установлен на 12:00>"
removeStandupTimeWithUsers = "Время для стэндапов в этом канале удалено, но остались стэндаперы!"
removeStandupTime = "Стэндап время для канала %s удалено" 

showNoStandupTime = "У этого канала до сих пор не установленно стэндап время! Пожалуйста, установите время слэшкомандой `/standup_time_set`!"
showStandupTime = "<!date^%v^Срок для стэндапов установлен на {time}|Срок для стэндапов установлен на 12:00>"

wrongNArgs = "Неверное количество аргументов. Перепроверьте свои данные!"
reportByProjectAndUser = "Данный пользователь не установлен как стэндапер в этом канале. Для начала добавьте его слэшкомандой `/comedian_add`"
reportOnProjectHead = "Полный отчет по проекту #%s с %v по %v:\n\n"
reportOnProjectCollectorData = "\nКоммитов за период: %v\nВорклогов за период: %v\n"
reportOnUserHead = "Полный отчет по пользователю <@%s> с %v по %v:\n\n"
reportOnProjectAndUserHead = "Отчет по пользователю <@%s> в проекте #%s с %v по %v:\n\n"

reportNoData = "Нет данных за данный период"
reportDate = "Отчет за %s:\n"
reportStandupFromUser = "\nСтэндап от <@%s>:\n%s\n"
reportIgnoredStandup = "\n<@%s>: стэндап пропущен!\n"
reportShowChannel = "В канале: <#%s>"
reportCollectorDataUser = "\nКоммитов: %v \nЧасов ворклогов: %v\n\n"
dateError1 = "Дата начала больше чем дата конца периуда"
dateError2 = "Дата конца отчёта указана в будущем времени"
userDidNotStandup = "<@%v> не написал стэндап!\n"
userDidStandup = "<@%v> написал стэндап!\n"
userDidNotStandupInChannel = "В #%v <@%v> не написал стэндап!\n"
userDidStandupInChannel = "В #%v <@%v> написал стэндап!\n"
PMAssigned = "Вас назначили админом Комедиана"
PMRemoved = "Вы больше не админ Комедиана"


helloManager = "Привет, менеджер!"
standupAccepted = "Отличная работа! Стэндап принят! Бомби дальше!"

p1 = "роблем"
p2 = "рудност"
p3 = "атрдуднен"
p4 = "опрос"

y1 = "чера"
y2 = "ятниц"
y3 = "делал"
y4 = "делано"
		
t1 = "егодн"
t2 = "обираюс"
t3 = "ланир"

notifyNotAll = "В этом канале не все написали стэндапы! Проигнорировали: %v"
notifyAllDone = "Поздравляю, сегодня все написали стэндапы!"
notifyManagerAllDone = "<@%v>, в канале <#%s> все написали стэндапы сегодня"
notifyManagerNotAll = "<@%v>, в канале <#%s> не все написали стэндапы сегодня, игнорировали: %v."
notifyUsersWarning = "%v, команда всё еще ждет стэндапы от вас! Осталось %v минут до дедлайна!"
notifyDirectMessage = "Привет, <@%s>! У тебя пропущен срок по стэндапам в канале <#%s|%s>. Пожалуйста, напиши стэндап! Чем скорее тем лучше!"


noWorklogs = " ворклоги: %v :angry: "
noCommits = " коммиты: %v :shit: "
noStandup = " стэндап :x: "

hasWorklogs = " ворклоги %v :muscle: "
hasCommits = " коммиты: %v :tada: "
hasStandup = " стэндап :heavy_check_mark: "

isRook = "<@%v> в #%v"

wrongUsernameError = "Кажется, вы допустили ошибку в имени пользователя. Пожалуйста, перепроверьте и попытайтесь еще раз!"

selectUsersToAdd = "Укажите пользователей, которых нужно добавить"
selectUsersToDelete = "Укажите пользователей, которых нужно удалить"
userDoesNotStandup = "Пользователь <@%v> не стэндапит в этом канале\n"
selectUsersToAddAsAdmin = "Укажите пользователей, которых нужно сделать админами"
noSuchUserInWorkspace = "Такого пользователя нет в вашем слаке"
userNotAdmin = "Этот пользователь не админ!"
wrongProjectName = "Неверное название проекта!"

DaysDivider = " по "
TimeDivider = " в " 
TimetableNoUsers = "Выберите стэндаперов!"
TimetableCreated = "Расписание для <@%v> создано: %v \n"

TimetableUpdated = "Расписание для <@%v> обновлено: %v \n"
CanNotUpdateTimetable = "Не смог обновить расписание для <@%v>: %v\n"
NotAStanduper = "Кажется <@%v> не стэндапит в этом канале!\n"
NoTimetableSet = "У <@%v> не установлено расписание!\n"
TimetableShow = "Расписание для <@%v>: %v\n"

CanNotDeleteTimetable = "Не смог создать расписание для <@%v>\n"
TimetableDeleted = "Расписание <@%v> успешно удалено! Теперь он стэндапится по общему графику\n"

IndividualStandupersWarning = "Внимание <@%s>! Кажется, твоего стэндапа до сих пор нет, а через %v минут уже последний срок! Поторопись!"
IndividualStandupersLate = "<@%v>, сроки пропущены! Пожалуйста, напиши стэндап как можно скорее!"
EmptyTimetable = "Свободный график"

TimetableShowMonday = "| Понедельник %02d:%02d "
TimetableShowTuesday = "| Вторник %02d:%02d "
TimetableShowWednesday = "| Среда %02d:%02d "
TimetableShowThursday = "| Четверг %02d:%02d "
TimetableShowFriday = "| Пятница %02d:%02d "
TimetableShowSaturday = "| Суббота %02d:%02d "
TimetableShowSunday = "| Воскресенье %02d:%02d "
ComedianIsNotInChannel = "У меня нет информации об этом канале. Кажется, меня не добавили в канал... Если я в канале, пожалуйста добавьте меня заново и попробуйте еще раз!"


StandupHandleUserNotAssigned = "Не могу принять твой стэндап так как ты не должен стэндапить в этом канале. Попроси ПМа тебя добавить и попробуй снова! Буду ждать!"
StandupHandleOneDayOneStandup = "Один день - один стэндап. Если хочешь поменять свой стэндап, лучше отредактируй старый!"
StandupHandleCouldNotSaveStandup = "По какой-то непонятной причине я не смог сохранить твой стэндап в базе. Прости пожалуйста и расскажи об этом ПМу!"
StandupHandleNoProblemsMentioned = "Не увидел твоих проблем и мне не верится, что у тебя их нет! Обяз опиши проблемы нормально!"
StandupHandleNoYesterdayWorkMentioned = "Так и не понял, что ты делал вчера. Напиши подробней пожалуйста!"
StandupHandleNoTodayPlansMentioned = "Всё вроде как есть, но что ты будешь делать сегодня мне не ясно. Если это не ясно мне, скорее всего и команде это не ясно. Дописывай!"
StandupHandleUpdatedStandup = "Отредактировал стэндап! Всё отлично!"
StandupHandleCreatedStandup = "Сохранил твой стэндап! Всё супер!"

ErrorRooksReportWeekend = "Сегодня выходной! Следующий отчет в понедельник!"

ReportHeaderMonday = "Отчёт за прошлую пятницу и выходные"    
ReportHeader = "Отчет за вчерашний день" 