[HelloManager]
description = "Greeting message once bot starts working"
other = "Привет <@{{.ID}}>"

[ListNoStandupers]
description = "Displays message when there are no standupers in the channel"
other = "В проекте никто не стэндапится! Чтобы добавить стендаперов воспользуйтесь командой `/comedian add`"