version: '2'

networks:
  comedian:
    driver: bridge

services:
  nginx:
    container_name: nginx
    image: nginx:1.13-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./configs/nginx/conf.d:/etc/nginx/conf.d
      - ./configs/nginx/vhost.d:/etc/nginx/vhost.d
      - ./configs/nginx/html:/usr/share/nginx/html
      - ./configs/nginx/certs:/etc/nginx/certs:ro
    networks:
      - comedian

  nginx-gen:
    container_name: nginx-gen
    image: jwilder/docker-gen
    restart: always
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - ./configs/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - comedian
    depends_on:
      - nginx

  nginx-letsencrypt:
    container_name: nginx-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-gen
      NGINX_PROXY_CONTAINER: nginx
    volumes_from:
      - nginx
    volumes:
      - ./configs/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - comedian
    depends_on:
      - nginx-gen
