version: '2.2'
networks:
  comedian_comedian:
    external: true

services:

  staging-db:
    image: percona/percona-server:5.7
    restart: on-failure
    command: --max_allowed_packet=32505856                                                                                                                                                     
    environment:                                                                                                                                                                               
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}                                                                                                                                             
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - comedian_comedian
    volumes:
      - ./percona:/var/lib/mysql:rw
    logging:
      driver: syslog
      options:
        tag: "docker/staging-comedian-db"

  staging-comedian:
    image: registry.gitlab.com/team-monitoring/comedian:staging
    restart: on-failure
    links:
      - staging-db:staging-db
    networks:
      - comedian_comedian
    expose: 
      - 8080
    environment:
      - COMEDIAN_DATABASE=${MADDEVS_COMEDIAN_DATABASE}
      - COMEDIAN_HTTP_BIND_ADDR=0.0.0.0:8080
      - COMEDIAN_SLACK_CLIENT_ID=${MADDEVS_COMEDIAN_SLACK_CLIENT_ID}
      - COMEDIAN_SLACK_CLIENT_SECRET=${MADDEVS_COMEDIAN_SLACK_CLIENT_SECRET}
      - SENTRY_DSN=${SENTRY_DSN}
      - SENTRY_ENVIRONMENT=comedian
      - VIRTUAL_HOST=staging.comedian.maddevs.co
      - LETSENCRYPT_HOST=staging.comedian.maddevs.co
      - LETSENCRYPT_EMAIL=fedorenko.tolik@gmail.com
    depends_on:
      - staging-db
    logging:
      driver: syslog
      options:
        tag: "docker/staging-comedian"